# This is a basic workflow to help you get started with Actions

name: Periodic broken links checker

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    # Runs at 7:00 AM CET every day
    - cron: '0 5 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  links-checker:
    name: Check for broken links in .md files

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Run the Milv broken links checker against the checked out repository
      - uses: docker://majakurcius/milv:0.0.1
        name: Run the Milv checker


